if(!localStorage.getItem('crm_session_token')){window.location.replace('/login');throw new Error('authentication_required');}
const data=[['1','Свободен','free'],['2','Занят','busy'],['3','Свободен','free'],['4','Бронь 21:30','reserve'],['5','Свободен','free'],['6','Занят','busy'],['7','Свободен','free'],['8','Занят','sel busy'],['9','Бронь 22:00','reserve'],['10','Свободен','free'],['11','Занят','busy'],['12','Ожидает оплату','']];
const roleFromUrl=new URLSearchParams(location.search).get('role')||'bartender';
const sessionHeaders=()=>{const token=localStorage.getItem('crm_session_token');return token?{Authorization:'Bearer '+token}:{};};
fetch('/api/session?role='+encodeURIComponent(roleFromUrl),{headers:sessionHeaders()}).then(r=>{if(r.status===401){window.location.href='/login';return null;} return r.ok?r.json():null;}).then(s=>{if(!s)return; document.querySelectorAll('nav button[data-permission]').forEach(btn=>{if(!s.permissions.includes(btn.dataset.permission))btn.hidden=true;}); const user=document.querySelector('.user'); if(user)user.innerHTML='● &nbsp; '+s.user.name+'<br><small>'+s.user.role+'</small>';}).catch(()=>{});
const tables=document.querySelector('#tables'); tables.innerHTML=data.map(([n,s,c])=>`<button class="table ${c}" data-table="${n}"><strong>${n}</strong><em>${s}</em><small>2–4 гостя</small></button>`).join('');
let openOrders=[];
let currentOrder=null;
let serverZones=[];
const tableMinimums={ 'vip-room-1':1500, 'vip-room-2':2500 };
const orderHeaders=()=>({...sessionHeaders(),'Content-Type':'application/json'});
const staticStaffDemo=()=>String(localStorage.getItem('crm_session_token')||'').startsWith('demo-static-');
const localOrders=()=>{try{return JSON.parse(localStorage.getItem('territory_crm_staff_orders')||'[]');}catch(_){return[];}};
const saveLocalOrders=(items)=>localStorage.setItem('territory_crm_staff_orders',JSON.stringify(items));
const staticOrderApi=async(url,options={})=>{const path=new URL(url,location.origin).pathname;const method=options.method||'GET';const input=options.body?JSON.parse(options.body):{};let list=localOrders();if(path==='/api/orders'&&method==='GET')return{items:list};if(path==='/api/orders'&&method==='POST'){const order={id:`local-order-${Date.now()}`,tableId:input.tableId||'table-8',minimumOrderTotal:Number(input.minimumOrderTotal||0),status:'open',items:[]};list.push(order);saveLocalOrders(list);return order;}const item=path.match(/^\/api\/orders\/([^/]+)\/items$/);if(item&&method==='POST'){const order=list.find(x=>x.id===item[1]);const product=products.find(x=>x[4]===input.productId||x[0]===input.productId);const added={id:`local-item-${Date.now()}`,productId:input.productId,name:product?.[0]||input.productId,quantity:Number(input.quantity||1),unitPrice:Number(product?.[1]||0)};if(order)order.items.push(added);saveLocalOrders(list);return added;}const action=path.match(/^\/api\/orders\/([^/]+)\/(status|transfer|close|discount-requests)$/);if(action){const order=list.find(x=>x.id===action[1]);if(!order)throw new Error('HTTP 404');if(action[2]==='status')order.status=input.status;if(action[2]==='transfer')order.tableId=input.tableId;if(action[2]==='close'){order.status='closed';const subtotal=(order.items||[]).reduce((s,x)=>s+x.unitPrice*x.quantity,0);order.subtotal=subtotal;order.finalTotal=Math.max(subtotal,Number(order.minimumOrderTotal||0));order.minimumAdjustment=Math.max(0,Number(order.minimumOrderTotal||0)-subtotal);order.paymentMethod=input.paymentMethod||'cash';}saveLocalOrders(list);return order;}return{};};
const apiJson=(url,options={})=>staticStaffDemo()?staticOrderApi(url,options):fetch(url,{...options,headers:{...sessionHeaders(),...(options.headers||{})}}).then(r=>r.ok?r.json():Promise.reject(new Error(`HTTP ${r.status}`)));
const orderRows=document.querySelector('.items');
function drawOrder(order){
  currentOrder=order||null;
  const title=document.querySelector('.order h2');
  const tableLabel=order?.tableId ? ({'vip-room-1':'VIP-комната 1','vip-room-2':'VIP-комната 2'}[String(order.tableId)]||`Стол ${String(order.tableId).replace(/^table-/,'')}`) : 'Стол 8';
  if(title) title.textContent=tableLabel;
  if(!orderRows)return;
  const items=order?.items||[];
  orderRows.innerHTML=items.length?items.map(item=>`<div>${item.name||item.productName||'Позиция'} ×${item.quantity||1}<b>${Number(item.unitPrice||item.price||0)*(item.quantity||1)} ₽</b></div>`).join(''):'<div class="empty-order">Позиции пока не добавлены</div>';
  recalc();
}
function loadOrders(){return apiJson('/api/orders').then(payload=>{openOrders=payload.items||[]; const selected=openOrders.find(o=>String(o.tableId)==='table-8'||String(o.tableId)==='8'); drawOrder(selected||{tableId:'table-8',items:[]});}).catch(()=>drawOrder({tableId:'table-8',items:[]}));}
loadOrders();
const renderZone=(zone)=>{const serverTables=zone?.tables||[]; if(!serverTables.length)return; serverTables.forEach((t)=>{tableMinimums[t.id]=Number(t.minimumOrderTotal||0);}); tables.innerHTML=serverTables.map(t=>{const label=t.status==='occupied'?'Занят':t.status==='reserved'?'Бронь':'Свободен'; return `<button class="table ${t.status==='occupied'?'busy':t.status==='reserved'?'reserve':'free'} ${t.name==='Стол 8'?'sel':''}" data-table="${t.id}"><strong>${t.name.replace(/^Стол /,'')}</strong><em>${label}</em><small>${t.capacity||'2–4'} гостя</small></button>`}).join('');};
fetch('/api/floor',{headers:sessionHeaders()}).then(r=>r.ok?r.json():null).then(payload=>{serverZones=payload?.zones||[]; renderZone(serverZones[0]);}).catch(()=>{});
tables.addEventListener('click',event=>{const card=event.target.closest('.table'); if(!card)return; document.querySelectorAll('.table').forEach(x=>x.classList.remove('sel')); card.classList.add('sel'); const id=String(card.dataset.table).startsWith('table-')?card.dataset.table:`table-${card.dataset.table}`; const found=openOrders.find(o=>String(o.tableId)===id||String(o.tableId)===String(card.dataset.table)); if(found)drawOrder(found); else { currentOrder=null; document.querySelector('.order h2').textContent='Стол '+card.dataset.table; drawOrder({tableId:id,items:[]}); }});
const catalog=document.querySelector('#catalog'), grid=document.querySelector('#catalog-grid'), search=document.querySelector('#product-search');
let products=[['Кальян — Darkside Blueberry',1200,['кальян','darkside','blueberry'],null],['Лимонад Маракуйя',300,['лимонад','маракуйя','maracuya'],null],['Red Bull',250,['red bull','ред булл','энергетик'],null],['Чай Эрл Грей',300,['чай','earl grey'],null],['Чаша глиняная',500,['чаша'],null],['Уголь Coco Nara',600,['уголь','coco nara'],null]];
function draw(q=''){grid.innerHTML=products.filter(([name,,aliases=[]])=>[name,...aliases].join(' ').toLowerCase().includes(q.toLowerCase())).map(([name,price,aliases=[],imageUrl])=>{const id=products.find(x=>x[0]===name)?.[4]||name.toLowerCase().replace(/[^a-z0-9]+/g,'-'); return `<button class="product" data-id="${id}" data-name="${name}" data-price="${price}">${imageUrl?`<img src="${imageUrl}" alt="">`:'<span class="product-placeholder">＋</span>'}<span>${name}</span><b>${price} ₽ &nbsp;＋</b></button>`;}).join('');}
draw(); fetch('/api/products',{headers:sessionHeaders()}).then(r=>r.ok?r.json():null).then(data=>{if(data?.items?.length){products=data.items.map(x=>[x.name,x.price,x.aliases||[],x.imageUrl||null,x.id]);draw(search?.value||'');}}).catch(()=>{}); document.querySelector('.primary')?.addEventListener('click',()=>catalog.classList.add('open')); document.querySelector('#catalog-close')?.addEventListener('click',()=>catalog.classList.remove('open')); search?.addEventListener('input',e=>draw(e.target.value));
function recalc(){const total=[...document.querySelectorAll('.items b')].reduce((s,x)=>s+Number(x.textContent.replace(/[^0-9]/g,'')),0); const el=document.querySelector('#order-total'); if(el)el.textContent=total.toLocaleString('ru-RU')+' ₽';}
grid.addEventListener('click',e=>{const item=e.target.closest('.product'); if(!item)return; const add=order=>apiJson(`/api/orders/${order.id}/items`,{method:'POST',headers:orderHeaders(),body:JSON.stringify({productId:item.dataset.id||item.dataset.name.toLowerCase().replace(/[^a-z0-9]+/g,'-'),quantity:1})}); const finish=order=>add(order).then(created=>{order.items=[...(order.items||[]),{...created,name:created.name||item.dataset.name,unitPrice:Number(item.dataset.price)}]; drawOrder(order); catalog.classList.remove('open');}).catch(()=>{const row=document.createElement('div'); row.innerHTML=`${item.dataset.name} <b>${item.dataset.price} ₽</b>`; orderRows.append(row); recalc(); catalog.classList.remove('open');}); if(currentOrder?.id) finish(currentOrder); else {const tableId=document.querySelector('.table.sel')?.dataset.table||'8'; apiJson('/api/orders',{method:'POST',headers:orderHeaders(),body:JSON.stringify({tableId:String(tableId).startsWith('table-')?tableId:`table-${tableId}`,minimumOrderTotal:tableMinimums[tableId]||0})}).then(order=>{openOrders.push(order);finish(order);}).catch(()=>finish({id:'local-order',tableId,minimumOrderTotal:tableMinimums[tableId]||0,items:[]})); }});
document.querySelector('.close')?.addEventListener('click',()=>{if(!currentOrder?.id){alert('Сначала добавьте позицию в заказ');return;} const method=window.prompt('Способ оплаты: cash, card или qr','cash')||'cash'; apiJson(`/api/orders/${currentOrder.id}/close`,{method:'POST',headers:orderHeaders(),body:JSON.stringify({paymentMethod:method})}).then(result=>{alert(`Заказ закрыт на ${Number(result.finalTotal||0).toLocaleString('ru-RU')} ₽`); currentOrder=null; drawOrder({items:[]});}).catch(()=>alert('Не удалось закрыть заказ'));});
document.querySelector('#discount-request')?.addEventListener('click',()=>{if(!currentOrder?.id){alert('Сначала откройте заказ');return;} const value=Number(window.prompt('Размер скидки, %','10')); if(!Number.isFinite(value)||value<=0||value>100)return; const reason=window.prompt('Причина скидки','Лояльность гостя'); if(!reason)return; apiJson(`/api/orders/${currentOrder.id}/discount-requests`,{method:'POST',headers:orderHeaders(),body:JSON.stringify({type:'percent',value,reason})}).then(()=>alert('Заявка отправлена администратору')).catch(()=>alert('Не удалось отправить заявку'));});

const notice=(text)=>{let el=document.querySelector('#staff-notice');if(!el){el=document.createElement('div');el.id='staff-notice';el.className='staff-notice';document.body.append(el);}el.textContent=text;el.classList.add('show');clearTimeout(el._timer);el._timer=setTimeout(()=>el.classList.remove('show'),2400);};
document.querySelectorAll('aside nav button').forEach((button)=>button.addEventListener('click',()=>{
  document.querySelectorAll('aside nav button').forEach((item)=>item.classList.remove('active')); button.classList.add('active');
  const label=button.textContent.trim(); if(label.includes('Бронирования')) window.location.href='/reservations'; else if(label.includes('Заказы')||label.includes('Задачи')) document.querySelector('.queue')?.scrollIntoView({behavior:'smooth'}); else document.querySelector('.tables')?.scrollIntoView({behavior:'smooth'});
}));
document.querySelectorAll('.tabs button').forEach((button)=>button.addEventListener('click',()=>{document.querySelectorAll('.tabs button').forEach((item)=>item.classList.remove('selected'));button.classList.add('selected');const zone=serverZones.find((item)=>item.name.toLowerCase().includes(button.textContent.trim().toLowerCase()));if(zone)renderZone(zone);notice(`Зона «${button.textContent.trim()}» выбрана`);}));
document.querySelectorAll('.actions button').forEach((button)=>button.addEventListener('click',()=>{
  if(!currentOrder?.id){notice('Сначала добавьте позицию в заказ');return;}
  const status=button.textContent.includes('бар')?'in_progress':'ready';
  apiJson(`/api/orders/${currentOrder.id}/status`,{method:'POST',headers:orderHeaders(),body:JSON.stringify({status})}).then(()=>{currentOrder.status=status;notice(status==='in_progress'?'Заказ отправлен на бар':'Задача отправлена кальянщику');}).catch(()=>notice('Не удалось передать заказ'));
}));
document.querySelector('.secondary:not(#discount-request)')?.addEventListener('click',()=>{
  if(!currentOrder?.id){notice('Сначала откройте заказ');return;}
  const table=window.prompt('Номер нового стола','1'); if(!table)return; const tableId=String(table).startsWith('table-')?String(table):`table-${table}`;
  apiJson(`/api/orders/${currentOrder.id}/transfer`,{method:'POST',headers:orderHeaders(),body:JSON.stringify({tableId})}).then(()=>{currentOrder.tableId=tableId;document.querySelector('.order h2').textContent=`Стол ${String(table).replace(/^table-/,'')}`;notice('Заказ передан на новый стол');}).catch(()=>notice('Не удалось передать заказ'));
});
document.querySelectorAll('.order-tabs span').forEach((tab)=>tab.addEventListener('click',()=>notice(`${tab.textContent.trim()}: раздел готов к заполнению`)));
document.querySelectorAll('.chips span').forEach((chip)=>chip.addEventListener('click',()=>{document.querySelectorAll('.chips span').forEach((item)=>item.classList.remove('active'));chip.classList.add('active');notice(`Фильтр «${chip.textContent.trim()}» применён`);}));

