const data=[['1','Свободен','free'],['2','Занят','busy'],['3','Свободен','free'],['4','Бронь 21:30','reserve'],['5','Свободен','free'],['6','Занят','busy'],['7','Свободен','free'],['8','Занят','sel busy'],['9','Бронь 22:00','reserve'],['10','Свободен','free'],['11','Занят','busy'],['12','Ожидает оплату','']];
const roleFromUrl=new URLSearchParams(location.search).get('role')||'bartender';
const sessionHeaders=()=>{const token=localStorage.getItem('crm_session_token');return token?{Authorization:'Bearer '+token}:{};};
fetch('/api/session?role='+encodeURIComponent(roleFromUrl),{headers:sessionHeaders()}).then(r=>r.ok?r.json():null).then(s=>{if(!s)return; const permissionByLabel={'Склад':'inventory','Финансы':'finance','Сотрудники':'staff','Настройки':'settings'}; document.querySelectorAll('nav button').forEach(btn=>{const permission=permissionByLabel[btn.textContent.trim()]; if(permission&&!s.permissions.includes(permission))btn.hidden=true;}); const user=document.querySelector('.user'); if(user)user.innerHTML='● &nbsp; '+s.user.name+'<br><small>'+s.user.role+'</small>';}).catch(()=>{});
const tables=document.querySelector('#tables'); tables.innerHTML=data.map(([n,s,c])=>`<button class="table ${c}" data-table="${n}"><strong>${n}</strong><em>${s}</em><small>2–4 гостя</small></button>`).join('');
fetch('/api/floor',{headers:sessionHeaders()}).then(r=>r.ok?r.json():null).then(payload=>{const serverTables=payload?.zones?.[0]?.tables||[]; if(!serverTables.length)return; tables.innerHTML=serverTables.map(t=>{const label=t.status==='occupied'?'Занят':t.status==='reserved'?'Бронь':'Свободен'; return `<button class="table ${t.status==='occupied'?'busy':t.status==='reserved'?'reserve':'free'} ${t.name==='Стол 8'?'sel':''}" data-table="${t.id}"><strong>${t.name.replace('Стол ','')}</strong><em>${label}</em><small>2–4 гостя</small></button>`}).join('');}).catch(()=>{});
tables.addEventListener('click',event=>{const card=event.target.closest('.table'); if(!card)return; document.querySelectorAll('.table').forEach(x=>x.classList.remove('sel')); card.classList.add('sel'); document.querySelector('.order h2').textContent='Стол '+card.dataset.table;});
const catalog=document.querySelector('#catalog'), grid=document.querySelector('#catalog-grid'), search=document.querySelector('#product-search');
let products=[['Кальян — Darkside Blueberry',1200,['кальян','darkside','blueberry'],null],['Лимонад Маракуйя',300,['лимонад','маракуйя','maracuya'],null],['Red Bull',250,['red bull','ред булл','энергетик'],null],['Чай Эрл Грей',300,['чай','earl grey'],null],['Чаша глиняная',500,['чаша'],null],['Уголь Coco Nara',600,['уголь','coco nara'],null]];
function draw(q=''){grid.innerHTML=products.filter(([name,,aliases=[]])=>[name,...aliases].join(' ').toLowerCase().includes(q.toLowerCase())).map(([name,price,,imageUrl])=>`<button class="product" data-name="${name}" data-price="${price}">${imageUrl?`<img src="${imageUrl}" alt="">`:'<span class="product-placeholder">＋</span>'}<span>${name}</span><b>${price} ₽ &nbsp;＋</b></button>`).join('');}
draw(); fetch('/api/products',{headers:sessionHeaders()}).then(r=>r.ok?r.json():null).then(data=>{if(data?.items?.length){products=data.items.map(x=>[x.name,x.price,x.aliases||[],x.imageUrl||null]);draw(search?.value||'');}}).catch(()=>{}); document.querySelector('.primary')?.addEventListener('click',()=>catalog.classList.add('open')); document.querySelector('#catalog-close')?.addEventListener('click',()=>catalog.classList.remove('open')); search?.addEventListener('input',e=>draw(e.target.value));
function recalc(){const total=[...document.querySelectorAll('.items b')].reduce((s,x)=>s+Number(x.textContent.replace(/[^0-9]/g,'')),0); const el=document.querySelector('#order-total'); if(el)el.textContent=total.toLocaleString('ru-RU')+' ₽';}
grid.addEventListener('click',e=>{const item=e.target.closest('.product'); if(!item)return; const row=document.createElement('div'); row.innerHTML=`${item.dataset.name} <b>${item.dataset.price} ₽</b>`; document.querySelector('.items').append(row); recalc(); catalog.classList.remove('open');});
document.querySelector('.close')?.addEventListener('click',()=>alert('Закрытие стола потребует подтверждения и выбора способа оплаты'));

