(() => {
  const $ = (selector, root = document) => root.querySelector(selector);
  const state = { companies: [] };
  const api = async (url, options = {}) => { const response = await fetch(url, { credentials: 'same-origin', headers: { 'Content-Type': 'application/json', ...(options.headers || {}) }, ...options }); const payload = await response.json().catch(() => ({})); if (response.status === 401) { location.href = '/login?next=/platform'; throw new Error('authentication_required'); } if (response.status === 403) throw new Error('Доступ только владельцу SaaS'); if (!response.ok) throw new Error(payload.error || `HTTP ${response.status}`); return payload; };
  const money = (value) => String(value || '').replace(/^./, (char) => char.toUpperCase());
  const planLabel = (value) => ({ starter: 'Starter', growth: 'Growth', network: 'Network', enterprise: 'Enterprise' }[value] || value || 'Starter');
  const renderPlans = (payload) => { const plans = payload.plans || {}; $('#plan-cards').innerHTML = Object.entries(plans).map(([key, plan]) => `<article class="plan-card ${key === 'starter' ? 'selected' : ''}"><div class="plan-card-top"><b>${plan.name}</b><span>0 ₽/мес</span></div><p>${plan.description}</p><div class="plan-limits"><span>${plan.seatsLimit >= 9999 ? 'Безлимит' : plan.seatsLimit} мест</span><span>${plan.venuesLimit >= 9999 ? 'Безлимит' : plan.venuesLimit} завед.</span></div></article>`).join(''); };
  const renderKpis = (overview) => { $('#platform-kpis').innerHTML = `<article><span>Всего компаний</span><strong>${overview.companies}</strong><small>в реестре платформы</small></article><article><span>Активные</span><strong>${overview.activeCompanies}</strong><small>CRM-контуров работают</small></article><article><span>Пробный период</span><strong>${overview.trials}</strong><small>готовы к онбордингу</small></article><article><span>Состояние</span><strong class="good-text">99.9%</strong><small>доступность API</small></article>`; };
  const renderCompanies = () => { const query = String($('#company-search').value || '').trim().toLowerCase(); const items = state.companies.filter((item) => `${item.name} ${item.city} ${item.slug}`.toLowerCase().includes(query)); $('#companies-body').innerHTML = items.map((item) => `<tr><td><div class="company-name"><span class="company-avatar">${(item.name || 'C').slice(0, 1)}</span><div><b>${item.name}</b><small>${item.slug}</small></div></div></td><td>${item.city || '—'}</td><td><select class="plan-select" data-org-plan="${item.id}" aria-label="Тариф ${item.name}"><option value="starter" ${item.plan === 'starter' ? 'selected' : ''}>Starter</option><option value="growth" ${item.plan === 'growth' ? 'selected' : ''}>Growth</option><option value="network" ${item.plan === 'network' ? 'selected' : ''}>Network</option><option value="enterprise" ${item.plan === 'enterprise' ? 'selected' : ''}>Enterprise</option></select></td><td>${item.venues || 0}</td><td>${item.seats || 0}</td><td><span class="state-pill ${item.isActive !== false ? 'active' : 'paused'}">${item.isActive !== false ? 'Активна' : 'Приостановлена'}</span></td><td><button class="table-action" data-org-id="${item.id}" type="button">Открыть</button></td></tr>`).join('') || `<tr><td colspan="7" class="empty-state">Компаний пока нет</td></tr>`; };
  const load = async () => { try { const [overview, companies, plans] = await Promise.all([api('/api/platform/overview'), api('/api/platform/organizations'), api('/api/platform/plans')]); renderKpis(overview); renderPlans(plans); state.companies = companies.items || []; renderCompanies(); $('#platform-updated').textContent = `Обновлено ${new Intl.DateTimeFormat('ru-RU', { hour: '2-digit', minute: '2-digit' }).format(new Date())}`; } catch (error) { $('#companies-body').innerHTML = `<tr><td colspan="7" class="empty-state">Нет доступа к Control Center: ${error.message}</td></tr>`; } };
  const modal = $('#company-modal'); const toggleModal = (open) => { modal.hidden = !open; if (open) modal.querySelector('input[name=name]').focus(); };
  $('#open-company').addEventListener('click', () => toggleModal(true)); $('#close-company').addEventListener('click', () => toggleModal(false)); $('#cancel-company').addEventListener('click', () => toggleModal(false)); $('#company-search').addEventListener('input', renderCompanies);
  $('#companies-body').addEventListener('change', async (event) => { const select = event.target.closest('[data-org-plan]'); if (!select) return; try { await api(`/api/platform/organizations/${select.dataset.orgPlan}/subscription`, { method: 'PATCH', body: JSON.stringify({ plan: select.value }) }); await load(); } catch (_) { alert('Не удалось обновить тариф.'); } });
  $('#companies-body').addEventListener('click', (event) => { const button = event.target.closest('[data-org-id]'); if (button) alert('Контур компании готов к подключению CRM.'); });
  $('#platform-logout').addEventListener('click', async () => { await api('/api/logout', { method: 'POST' }); location.href = '/login'; });
  $('#organization-form').addEventListener('submit', async (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); const error = $('#company-error'); error.textContent = ''; const payload = Object.fromEntries(form.entries()); try { await api('/api/platform/organizations', { method: 'POST', body: JSON.stringify(payload) }); toggleModal(false); event.currentTarget.reset(); await load(); } catch (e) { error.textContent = e.message === 'slug_already_exists' ? 'Такой slug уже занят.' : 'Не удалось создать организацию.'; } });
  load();
})();
