(() => {
  const $ = (selector, root = document) => root.querySelector(selector);
  const state = { companies: [], loadError: null, health: 'checking', owners: [], ownerEditing: null };
  const escapeHtml = (value) => String(value ?? '').replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char]));
  const api = async (url, options = {}) => { const response = await fetch(url, { credentials: 'same-origin', headers: { 'Content-Type': 'application/json', ...(options.headers || {}) }, ...options }); const payload = await response.json().catch(() => ({})); if (response.status === 401) { location.href = '/login?next=/platform'; throw new Error('Требуется войти в систему.'); } if (response.status === 403) throw new Error('Доступ только владельцу SaaS.'); if (!response.ok) throw new Error(payload.error || `HTTP ${response.status}`); return payload; };
  const planLabel = (value) => ({ starter: 'Starter', growth: 'Growth', network: 'Network', enterprise: 'Enterprise' }[value] || value || 'Starter');
  const statusLabel = (item) => ({ trialing: 'Пробный период', active: 'Активна', past_due: 'Требует внимания', cancelled: 'Приостановлена' }[item.status] || (item.isActive === false ? 'Приостановлена' : 'Активна'));
  const renderPlans = (payload) => { const plans = payload.plans || {}; $('#plan-cards').innerHTML = Object.entries(plans).map(([key, plan]) => `<article class="plan-card"><div class="plan-card-top"><b>${escapeHtml(plan.name || planLabel(key))}</b><span>${Number(plan.monthlyPrice || 0)} ₽/мес</span></div><p>${escapeHtml(plan.description || '')}</p><div class="plan-limits"><span>${plan.seatsLimit >= 9999 ? 'Безлимит' : Number(plan.seatsLimit)} мест</span><span>${plan.venuesLimit >= 9999 ? 'Безлимит' : Number(plan.venuesLimit)} завед.</span></div></article>`).join(''); };
  const renderKpis = (overview) => { $('#platform-kpis').innerHTML = `<article><span>Всего компаний</span><strong>${Number(overview.companies) || 0}</strong><small>в реестре платформы</small></article><article><span>Активные</span><strong>${Number(overview.activeCompanies) || 0}</strong><small>по данным сервера</small></article><article><span>Пробный период</span><strong>${Number(overview.trials) || 0}</strong><small>в пробном периоде</small></article><article><span>Состояние</span><strong class="${state.health === 'ok' ? 'good-text' : 'bad-text'}">${state.health === 'ok' ? 'Доступен' : 'Нет связи'}</strong><small>проверка API</small></article>`; };
  const renderHealth = () => { const healthy = state.health === 'ok'; $('.platform-header .live-dot').textContent = healthy ? '● API доступен' : '● API недоступен'; $('.platform-header .live-dot').classList.toggle('offline', !healthy); const healthCard = $('#health'); healthCard.querySelector('.status-dot').classList.toggle('good', healthy); healthCard.querySelector('b').textContent = healthy ? 'Сервис CRM и API доступны' : 'Нет подтверждения доступности CRM и API'; healthCard.querySelector('p').textContent = healthy ? 'Проверка API прошла успешно. Изоляция организаций задаётся серверной сессией.' : 'Не удалось подтвердить доступность. Повторите проверку после восстановления соединения.'; };
  const renderCompanies = () => { const query = String($('#company-search').value || '').trim().toLowerCase(); const items = state.companies.filter((item) => `${item.name} ${item.city} ${item.slug}`.toLowerCase().includes(query)); $('#companies-body').innerHTML = items.map((item) => { const label = statusLabel(item); const active = item.status ? item.status === 'active' || item.status === 'trialing' : item.isActive !== false; return `<tr><td><div class="company-name"><span class="company-avatar">${escapeHtml((item.name || 'C').slice(0, 1))}</span><div><b>${escapeHtml(item.name)}</b><small>${escapeHtml(item.slug)}</small></div></div></td><td>${escapeHtml(item.city || '—')}</td><td><select class="plan-select" data-org-plan="${escapeHtml(item.id)}" aria-label="Тариф ${escapeHtml(item.name)}"><option value="starter" ${item.plan === 'starter' ? 'selected' : ''}>Starter</option><option value="growth" ${item.plan === 'growth' ? 'selected' : ''}>Growth</option><option value="network" ${item.plan === 'network' ? 'selected' : ''}>Network</option><option value="enterprise" ${item.plan === 'enterprise' ? 'selected' : ''}>Enterprise</option></select></td><td>${Number(item.venues) || 0}</td><td>${Number(item.seats) || 0}</td><td><span class="state-pill ${active ? 'active' : 'paused'}">${escapeHtml(label)}</span></td><td><button class="table-action" data-org-id="${escapeHtml(item.id)}" type="button">Открыть</button></td></tr>`; }).join('') || `<tr><td colspan="7" class="empty-state">${state.loadError ? escapeHtml(state.loadError) : query ? 'Компании не найдены' : 'Компаний пока нет'}</td></tr>`; };
  const load = async () => { const table = $('#companies-body'); table.innerHTML = '<tr><td colspan="7" class="empty-state">Загрузка компаний…</td></tr>'; state.loadError = null; try { const [overview, companies, plans, health] = await Promise.all([api('/api/platform/overview'), api('/api/platform/organizations'), api('/api/platform/plans'), api('/api/health')]); state.health = health.status === 'ok' ? 'ok' : 'down'; renderKpis(overview); renderPlans(plans); renderHealth(); state.companies = companies.items || []; renderCompanies(); $('#platform-updated').textContent = `Проверено ${new Intl.DateTimeFormat('ru-RU', { hour: '2-digit', minute: '2-digit' }).format(new Date())}`; } catch (error) { state.loadError = `Не удалось загрузить данные: ${error.message}`; state.health = 'down'; renderHealth(); table.innerHTML = `<tr><td colspan="7" class="empty-state">${escapeHtml(state.loadError)} <button class="table-action" type="button" data-retry-load>Повторить</button></td></tr>`; $('#platform-kpis').innerHTML = '<article><span>Состояние</span><strong class="bad-text">Недоступно</strong><small>ошибка загрузки</small></article>'; $('#platform-updated').textContent = 'Проверка не удалась'; } };
  const modal = $('#company-modal'); const detailModal = $('#company-detail-modal'); let detailOrgId = null; let detailLoaded = false; let detailTrigger = null; let createTrigger = null;
  const ownerModal = $('#owner-modal'); const ownerForm = $('#owner-form'); let ownerTrigger = null;
  const ownerApi = (orgId, ownerId, method, body) => api(`/api/platform/organizations/${encodeURIComponent(orgId)}/owners${ownerId ? `/${encodeURIComponent(ownerId)}` : ''}`, { method, body: body ? JSON.stringify(body) : undefined });
  const renderOwners = () => { const box = $('#company-detail-owner'); const owners = state.owners || []; box.innerHTML = owners.length ? owners.map((owner, index) => `<div class="owner-row"><div class="owner-main"><strong>${escapeHtml(owner.name || owner.fullName || 'Без имени')}</strong><span>${escapeHtml(owner.login || owner.email || 'Почта не указана')}</span></div><em class="${owner.active === false || owner.isActive === false ? 'owner-status paused' : 'owner-status active'}">${owner.active === false || owner.isActive === false ? 'Заблокирован' : owner.isPrimary || owner.isMain || index === 0 ? 'Главный владелец' : 'Совладелец'}</em><div class="owner-actions"><button type="button" class="table-action" data-owner-edit="${escapeHtml(owner.id)}">Изменить</button><button type="button" class="table-action" data-owner-password="${escapeHtml(owner.id)}">Пароль</button><button type="button" class="table-action" data-owner-toggle="${escapeHtml(owner.id)}">${owner.active === false || owner.isActive === false ? 'Разблокировать' : 'Заблокировать'}</button>${!(owner.isPrimary || owner.isMain || index === 0) ? `<button type="button" class="table-action danger-action" data-owner-delete="${escapeHtml(owner.id)}">Удалить</button><button type="button" class="table-action" data-owner-primary="${escapeHtml(owner.id)}">Сделать главным</button>` : ''}</div></div>`).join('') : '<span>Владельцы не указаны</span>'; };
  const openOwner = (owner) => { state.ownerEditing = owner || null; $('#owner-modal-title').textContent = owner ? 'Изменить владельца' : 'Добавить владельца'; ownerForm.reset(); ownerForm.elements.name.value = owner?.name || owner?.fullName || ''; ownerForm.elements.login.value = owner?.login || owner?.email || ''; ownerForm.elements.isPrimary.checked = !!(owner?.isPrimary || owner?.isMain); ownerForm.elements.password.required = !owner; ownerForm.elements.password.placeholder = owner ? 'Оставьте пустым, чтобы не менять' : 'Не менее 8 символов'; ownerModal.hidden = false; ownerForm.elements.name.focus(); };
  const closeOwner = () => { ownerModal.hidden = true; state.ownerEditing = null; ownerTrigger?.focus(); };

  const toggleModal = (open) => { modal.hidden = !open; if (open) { createTrigger = document.activeElement; modal.querySelector('input[name=name]').focus(); } else createTrigger?.focus(); };
  const toggleDetail = (open) => { detailModal.hidden = !open; if (open) $('#company-detail-plan').focus(); else { detailOrgId = null; detailLoaded = false; $('#save-company-detail').disabled = true; detailTrigger?.focus(); } };
  const setBusy = (button, busy, label) => { if (!button.dataset.idleLabel) button.dataset.idleLabel = button.textContent.trim(); button.disabled = busy; button.textContent = busy ? label : button.dataset.idleLabel; };
  $('#open-company').addEventListener('click', () => toggleModal(true)); $('#close-company').addEventListener('click', () => toggleModal(false)); $('#cancel-company').addEventListener('click', () => toggleModal(false)); $('#company-search').addEventListener('input', renderCompanies);
  $('#companies-body').addEventListener('click', async (event) => {
    if (event.target.closest('[data-retry-load]')) { load(); return; }
    const button = event.target.closest('[data-org-id]'); if (!button) return;
    detailTrigger = button; detailOrgId = button.dataset.orgId; detailLoaded = false; $('#save-company-detail').disabled = true;
    const item = state.companies.find((entry) => entry.id === detailOrgId); if (!item) return;
    $('#company-detail-title').textContent = item.name; $('#company-detail-meta').textContent = `${item.city || 'Город не указан'} · ${item.venues || 0} заведений · ${item.seats || 0} сотрудников`; state.owners = Array.isArray(item.owners) ? item.owners : (item.ownerName ? [{ id: item.ownerId, name: item.ownerName, login: item.ownerLogin, active: item.ownerActive !== false, isPrimary: true }] : []); renderOwners();
    $('#company-detail-error').textContent = 'Загрузка подписки…'; $('#company-detail-plan').value = item.plan || 'starter'; $('#company-detail-status').value = item.status || (item.isActive === false ? 'cancelled' : 'trialing'); toggleDetail(true);
    try { const subscription = await api(`/api/platform/organizations/${encodeURIComponent(detailOrgId)}/subscription`); if (detailOrgId !== button.dataset.orgId) return; $('#company-detail-plan').value = subscription.plan || $('#company-detail-plan').value; $('#company-detail-status').value = subscription.status || $('#company-detail-status').value; $('#company-detail-error').textContent = ''; detailLoaded = true; $('#save-company-detail').disabled = false; } catch (error) { $('#company-detail-error').textContent = `Не удалось загрузить подписку: ${error.message}`; }
  });
  $('#companies-body').addEventListener('change', async (event) => { const select = event.target.closest('[data-org-plan]'); if (!select) return; const item = state.companies.find((entry) => entry.id === select.dataset.orgPlan); if (!item) return; const previous = item.plan; select.disabled = true; try { await api(`/api/platform/organizations/${encodeURIComponent(item.id)}/subscription`, { method: 'PATCH', body: JSON.stringify({ plan: select.value }) }); await load(); } catch (error) { select.value = previous; state.loadError = `Не удалось изменить тариф: ${error.message}`; alert(state.loadError); } finally { select.disabled = false; } });
  const refreshOwners = async () => { const fresh = await api('/api/platform/organizations'); state.companies = fresh.items || state.companies; state.owners = state.companies.find((entry) => entry.id === detailOrgId)?.owners || []; renderOwners(); };
  $('#add-owner').addEventListener('click', () => { ownerTrigger = document.activeElement; openOwner(); });
  $('#close-owner').addEventListener('click', closeOwner); $('#cancel-owner').addEventListener('click', closeOwner);
  $('#company-detail-owner').addEventListener('click', async (event) => { const btn = event.target.closest('button'); if (!btn || !detailOrgId) return; const id = Object.values(btn.dataset).find(Boolean); const owner = state.owners.find((entry) => String(entry.id) === String(id)); if (!owner) return; try { if (btn.dataset.ownerEdit) openOwner(owner); else if (btn.dataset.ownerPassword) { const password = prompt('Новый пароль (не менее 8 символов):'); if (!password || password.length < 8) return; await ownerApi(detailOrgId, owner.id, 'PATCH', { password }); alert('Пароль обновлён.'); await refreshOwners(); } else if (btn.dataset.ownerToggle) { if (!confirm('Изменить блокировку владельца?')) return; await ownerApi(detailOrgId, owner.id, 'PATCH', { active: !(owner.active !== false) }); await refreshOwners(); } else if (btn.dataset.ownerDelete) { if (!confirm('Удалить совладельца?')) return; await ownerApi(detailOrgId, owner.id, 'DELETE'); await refreshOwners(); } else if (btn.dataset.ownerPrimary) { if (!confirm('Передать статус главного владельца?')) return; await ownerApi(detailOrgId, owner.id, 'PATCH', { isPrimary: true }); await refreshOwners(); } } catch (error) { $('#owner-management-error').textContent = error.message; } });
  ownerForm.addEventListener('submit', async (event) => { event.preventDefault(); if (!detailOrgId) return; const data = Object.fromEntries(new FormData(ownerForm).entries()); const payload = { name: data.name, login: data.login, isPrimary: ownerForm.elements.isPrimary.checked }; if (data.password) payload.password = data.password; $('#owner-form-error').textContent = ''; try { await ownerApi(detailOrgId, state.ownerEditing?.id, state.ownerEditing ? 'PATCH' : 'POST', payload); closeOwner(); await refreshOwners(); } catch (error) { $('#owner-form-error').textContent = error.message; } });
  $('#close-company-detail').addEventListener('click', () => toggleDetail(false)); $('#cancel-company-detail').addEventListener('click', () => toggleDetail(false));
  $('#save-company-detail').addEventListener('click', async (event) => { if (!detailOrgId || !detailLoaded) return; const button = event.currentTarget; const error = $('#company-detail-error'); error.textContent = ''; setBusy(button, true, 'Сохранение…'); try { await api(`/api/platform/organizations/${encodeURIComponent(detailOrgId)}/subscription`, { method: 'PATCH', body: JSON.stringify({ plan: $('#company-detail-plan').value, status: $('#company-detail-status').value }) }); toggleDetail(false); await load(); } catch (e) { error.textContent = `Не удалось сохранить изменения: ${e.message}`; } finally { if (!detailModal.hidden) { button.disabled = !detailLoaded; button.textContent = button.dataset.idleLabel || 'Сохранить'; } } });
  document.addEventListener('keydown', (event) => { if (event.key !== 'Escape') return; if (!modal.hidden) toggleModal(false); if (!detailModal.hidden) toggleDetail(false); if (!ownerModal.hidden) closeOwner(); });
  $('#platform-logout').addEventListener('click', async (event) => { const button = event.currentTarget; setBusy(button, true, 'Выход…'); try { await api('/api/logout', { method: 'POST' }); location.href = '/login'; } catch (error) { alert(`Не удалось выйти: ${error.message}`); button.disabled = false; button.textContent = button.dataset.idleLabel || 'Выйти'; } });
  $('#organization-form').addEventListener('submit', async (event) => { event.preventDefault(); const formElement = event.currentTarget; if (formElement.dataset.submitting === 'true') return; const submit = formElement.querySelector('[type=submit]'); const form = new FormData(formElement); const error = $('#company-error'); error.textContent = ''; const payload = Object.fromEntries(form.entries()); formElement.dataset.submitting = 'true'; formElement.setAttribute('aria-busy', 'true'); setBusy(submit, true, 'Создание…'); try { await api('/api/platform/organizations', { method: 'POST', body: JSON.stringify(payload) }); toggleModal(false); formElement.reset(); await load(); } catch (e) { error.textContent = e.message === 'slug_or_owner_login_already_exists' ? 'Такой адрес компании или почта владельца уже заняты.' : e.message === 'valid_owner_credentials_required' ? 'Проверьте имя, рабочую почту и пароль владельца.' : e.message === 'invalid_organization_timezone' ? 'Не удалось определить часовой пояс.' : 'Не удалось создать компанию. Проверьте данные и повторите попытку.'; } finally { formElement.dataset.submitting = 'false'; formElement.removeAttribute('aria-busy'); submit.disabled = false; submit.textContent = submit.dataset.idleLabel || 'Создать организацию'; } });
  load();
})();

