(function mountStaffProfile(){
  const storageKey='crm_session_user';
  const readUser=()=>{try{return JSON.parse(localStorage.getItem(storageKey)||'{}');}catch(_){return{};}};
  const writeUser=(user)=>localStorage.setItem(storageKey,JSON.stringify(user));
  const sourceOf=(user)=>user.avatarUrl||user.avatar_url||user.avatar||user.photoUrl||user.photo_url||user.photo||'';
  const initials=(user)=>String(user.name||user.fullName||user.username||'С').trim().slice(0,1).toUpperCase();
  const renderAvatar=(host,user)=>{if(!host)return;let avatar=host.querySelector('.staff-profile-avatar');if(!avatar){avatar=document.createElement('span');avatar.className='staff-profile-avatar';host.prepend(avatar);}const source=sourceOf(user);avatar.textContent=source?'':initials(user);avatar.style.backgroundImage=source?'url("'+source.replace(/"/g,'')+'")':'';};
  const normalizePhones=(user)=>Array.isArray(user.phoneNumbers)?user.phoneNumbers.filter((phone)=>phone&&phone.number).map((phone,index)=>({label:String(phone.label||'Рабочий'),number:String(phone.number||'').trim(),primary:Boolean(phone.primary)||index===0})):[];
  const open=()=>{
    if(document.querySelector('.staff-profile-modal'))return;
    const user=readUser(); const modal=document.createElement('div'); modal.className='staff-profile-modal';
    modal.innerHTML='<div class="staff-profile-dialog" role="dialog" aria-modal="true" aria-label="Профиль сотрудника"><button type="button" class="staff-profile-close" aria-label="Закрыть">×</button><div class="staff-profile-dialog__heading"><span class="staff-profile-dialog__avatar staff-profile-preview">'+initials(user)+'</span><div><h2>Мой профиль</h2><p>Аватар и рабочие контакты</p></div></div><label class="staff-profile-field">Аватар<input type="file" class="staff-profile-file" accept="image/png,image/jpeg,image/webp"></label><label class="staff-profile-field">Telegram<input type="text" class="staff-profile-telegram" placeholder="@username или https://t.me/username"></label><div class="staff-profile-phones"><div class="staff-profile-phones__head"><b>Телефоны</b><button type="button" class="staff-profile-phone-add">Добавить номер</button></div><div class="staff-profile-phone-list"></div></div><p class="staff-profile-error" role="alert"></p><div class="staff-profile-actions"><button type="button" class="staff-profile-cancel">Отмена</button><button type="button" class="staff-profile-save">Сохранить</button></div></div>';
    document.body.append(modal);
    const preview=modal.querySelector('.staff-profile-preview'); const file=modal.querySelector('.staff-profile-file'); const telegram=modal.querySelector('.staff-profile-telegram'); const error=modal.querySelector('.staff-profile-error'); const phoneList=modal.querySelector('.staff-profile-phone-list');
    telegram.value=user.telegram||user.telegramUrl||'';
    const current=sourceOf(user); if(current){preview.textContent='';preview.style.backgroundImage='url("'+current.replace(/"/g,'')+'")';}
    const addPhone=(phone={})=>{const row=document.createElement('div');row.className='staff-profile-phone-row';row.innerHTML='<select aria-label="Тип телефона"><option>Рабочий</option><option>Личный</option><option>Резервный</option><option>Дополнительный</option></select><input type="tel" aria-label="Номер телефона" placeholder="+7 (___) ___-__-__"><label><input type="radio" name="profile_primary_phone"> основной</label><button type="button" aria-label="Удалить номер">×</button>';row.querySelector('select').value=phone.label||'Рабочий';row.querySelector('input[type="tel"]').value=phone.number||'';row.querySelector('input[type="radio"]').checked=Boolean(phone.primary);row.querySelector('button').addEventListener('click',()=>{if(phoneList.children.length>1)row.remove();else row.querySelector('input[type="tel"]').value='';});phoneList.append(row);};
    const phones=normalizePhones(user); (phones.length?phones:[{}]).forEach(addPhone);
    modal.querySelector('.staff-profile-phone-add').addEventListener('click',()=>addPhone());
    file.addEventListener('change',()=>{const selected=file.files?.[0];if(!selected)return;if(selected.size>2*1024*1024){error.textContent='Изображение должно быть не больше 2 МБ.';file.value='';return;}const reader=new FileReader();reader.onload=()=>{preview.textContent='';preview.style.backgroundImage='url("'+String(reader.result).replace(/"/g,'')+'")';preview.dataset.source=String(reader.result);};reader.readAsDataURL(selected);});
    const close=()=>modal.remove(); modal.querySelector('.staff-profile-close').addEventListener('click',close); modal.querySelector('.staff-profile-cancel').addEventListener('click',close); modal.addEventListener('click',(event)=>{if(event.target===modal)close();});
    modal.querySelector('.staff-profile-save').addEventListener('click',()=>{const value=telegram.value.trim();if(value&&!/^(@[A-Za-z0-9_]{5,32}|https:\/\/t\.me\/[A-Za-z0-9_]{5,32}\/?$)/.test(value)){error.textContent='Укажите @username или ссылку https://t.me/username.';return;}const phoneNumbers=[...phoneList.querySelectorAll('.staff-profile-phone-row')].map((row)=>({label:row.querySelector('select').value,number:row.querySelector('input[type="tel"]').value.trim(),primary:row.querySelector('input[type="radio"]').checked})).filter((phone)=>phone.number);if(phoneNumbers.length&&phoneNumbers.filter((phone)=>phone.primary).length!==1){error.textContent='Выберите один основной номер телефона.';return;}const next={...user,telegram:value,phoneNumbers};if(preview.dataset.source){next.avatarUrl=preview.dataset.source;next.avatar=preview.dataset.source;}writeUser(next);if(typeof window.__syncStaffProfile==='function')window.__syncStaffProfile(user,value,next.avatarUrl||'',phoneNumbers);renderAvatar(document.querySelector('.user'),next);close();});
  };
  const mount=()=>{const host=document.querySelector('.user');if(!host||host.dataset.staffProfileReady==='1')return;host.dataset.staffProfileReady='1';host.setAttribute('role','button');host.tabIndex=0;host.title='Открыть профиль';const user=readUser();renderAvatar(host,user);host.addEventListener('click',open);host.addEventListener('keydown',(event)=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();open();}});};
  mount(); new MutationObserver(mount).observe(document.body,{childList:true,subtree:true});
})();
;(function syncStaffProfileWithServer(){
  const original=window.fetch;
  if(typeof original!=='function'&&typeof window.__crmApi!=='function'||window.__staffProfileSyncWrapped)return;
  window.__staffProfileSyncWrapped=true;
  window.__syncStaffProfile=(user,value,avatar,phoneNumbers)=>{if(!user?.id)return;const headers=typeof window.sessionHeaders==='function'?window.sessionHeaders():{};headers['Content-Type']='application/json';const request={method:'PATCH',headers,body:JSON.stringify({telegram:value,avatarUrl:avatar||undefined,phoneNumbers:Array.isArray(phoneNumbers)?phoneNumbers:undefined})};const transport=typeof window.__crmApi==='function'?window.__crmApi:original;transport('/api/staff/'+encodeURIComponent(user.id)+'/profile',request).catch(()=>{});};
})();
