import assert from 'node:assert/strict';
import fs from 'node:fs';
const migration = fs.readFileSync('migrations/021_staff_time_payroll.sql', 'utf8');
const expenses = fs.readFileSync('migrations/022_expenses.sql', 'utf8');
const lifecycle = fs.readFileSync('migrations/040_payroll_lifecycle.sql', 'utf8');
const server = fs.readFileSync('server.js', 'utf8');
const payroll = fs.readFileSync('payroll.js', 'utf8');
for (const token of ['staff_schedules','staff_work_logs','payroll_rules','payroll_entries']) assert.match(migration, new RegExp(`CREATE TABLE IF NOT EXISTS ${token}`));
for (const route of ['/api/staff/schedule','/api/staff/time','/api/payroll/rules','/api/payroll/entries']) assert.match(server, new RegExp(route.replaceAll('/', '\\/')));
assert.match(server, /EXTRACT\(EPOCH FROM/);
assert.match(server, /calculatePayrollAmount\(\{ ruleType: rule\.rule_type/);
assert.match(payroll, /ruleType === 'hourly'/);
assert.match(server, /pathname === '\/api\/payroll\/entries' && req\.method === 'GET'/);
assert.match(server, /payrollEntryPath && req\.method === 'PATCH'/);
assert.match(server, /BEGIN/);
assert.match(server, /payroll_expense_must_be_paid_through_payroll/);
for (const status of ['approved','paid','cancelled']) assert.match(lifecycle, new RegExp(status));
assert.match(expenses, /CREATE TABLE IF NOT EXISTS expenses/);
assert.match(server, /\/api\/expenses/);
assert.match(server, /source.*payroll/);
assert.match(server, /source <> 'payroll'/);
assert.match(server, /source NOT IN \('payroll','purchase'\)/, 'purchase principal is cash flow, not an immediate P&L operating expense');
assert.match(server, /payrollNeedsReview/, 'legacy payroll expenses remain visible for reconciliation');
assert.match(server, /legacy_unmatched/, 'unlinked historical payroll expense gets an explicit review state');
assert.match(server, /pe\.period_to >= \$2::date/);
assert.match(server, /pe\.period_from <= \$3::date/);
assert.match(server, /AT TIME ZONE COALESCE\(NULLIF\(org\.timezone/);
assert.match(server, /COUNT\(DISTINCT shift_date\) FILTER \(WHERE is_shift_start\)/, 'split time logs on one business day count as one shift');
assert.match(server, /MAX\(ends_at\) OVER \(ORDER BY starts_at,ends_at/, 'overlapping historical logs cannot inflate payroll hours');
assert.match(server, /netProfit: revenue - expenses - costOfGoods/);
assert.match(server, /totalCashOutflow/);
console.log('PAYROLL QA: schedules, work time, calculated payroll lifecycle, expenses and P&L/cashflow separation wired');
